[package]
name = "vk-cholesky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26"
ash = "0.37.0+1.3.209"
ash-window = "0.11.0"