[package]
name = "vrx-graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vrx = { path = "../vrx", features=["graphics"] }
winit = "0.28.0"
paste = "1.0"

